// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbQ8k4M_hRMWD4FoB7UXeJT7pSYUIH9WY',
    appId: '1:1034729029149:web:cc437c440725899f0c10f4',
    messagingSenderId: '1034729029149',
    projectId: 'recetario-6e4c7',
    authDomain: 'recetario-6e4c7.firebaseapp.com',
    storageBucket: 'recetario-6e4c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP1XyqYahL4AZ53zu3VYzrwHImu0jBL2Y',
    appId: '1:1034729029149:android:45e33145c97282460c10f4',
    messagingSenderId: '1034729029149',
    projectId: 'recetario-6e4c7',
    storageBucket: 'recetario-6e4c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-TeRrz6CdeqwvALQa_3EQq2ubdcQxiP8',
    appId: '1:1034729029149:ios:95c94703ff52c1c20c10f4',
    messagingSenderId: '1034729029149',
    projectId: 'recetario-6e4c7',
    storageBucket: 'recetario-6e4c7.firebasestorage.app',
    iosBundleId: 'com.lsd.recetario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-TeRrz6CdeqwvALQa_3EQq2ubdcQxiP8',
    appId: '1:1034729029149:ios:95c94703ff52c1c20c10f4',
    messagingSenderId: '1034729029149',
    projectId: 'recetario-6e4c7',
    storageBucket: 'recetario-6e4c7.firebasestorage.app',
    iosBundleId: 'com.lsd.recetario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbQ8k4M_hRMWD4FoB7UXeJT7pSYUIH9WY',
    appId: '1:1034729029149:web:4ad8ca5153b8f0180c10f4',
    messagingSenderId: '1034729029149',
    projectId: 'recetario-6e4c7',
    authDomain: 'recetario-6e4c7.firebaseapp.com',
    storageBucket: 'recetario-6e4c7.firebasestorage.app',
  );
}
